services:
  - type: web
    name: wahm-sherlock
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: PUPPETEER_HEADLESS
        value: "true"
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
